# fly.toml app configuration file generated for http-snowy-fog-8462 on 2025-08-24T14:24:00+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'http-snowy-fog-8462'
primary_region = 'bom'

[build]
context = "../.."
dockerfile = "./dockerfile"

[http_service]
  internal_port = 3121
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
